### ISSUE TITLE
implementation of the covariance matrix

### ISSUE THREAD

**Issue by MichaelYu781** [govvijaycal/confidence_aware_predictions#1]
https://github.com/govvijaycal/confidence_aware_predictions/blob/main/scripts/models/multipath.py#L147

hi I have a question re above line
What is the theta here 
Why define covariance matrix using R(theta) which is different from conventional one in my understanding.

**Comment by govvijaycal** [comment]
Hi Michael,

Sorry for the late response.  I opted for using the eigendecomposition of the covariance matrix to avoid numerical issues when using the original approach, where you predict the correlation rho.  The angle theta basically sets up a rotation matrix that forms the eigenvectors of the covariance matrix.  When using the original method, if rho is high, then the covariance matrix can be singular and the log likelihood loss will be affected poorly.

You can certainly adjust back to the original format, but you may want to limit the range of rho and std_x, std_y to avoid this singularity issue.

Hope this helps!

**Comment by MichaelYu781** [comment]
Thanks for your answer
